export const InputHoverUp = () => {
  return (
    <div>
      <label
        htmlFor="nameForm"
        className="
          absolute
          z-10
          translate-x-6
          translate-y-2
          rounded-full
          bg-white
          text-black-500
          hover:text-black
        "
      >
        姓
      </label>
      <input
        type="text"
        className="
          absolute
          mr-4
          translate-x-3
          translate-y-1
          rounded-md
          border
          px-3
          py-1
          text-gray-400
          focus:translate-y-5
          focus:duration-300
          focus:ease-in-out
          "
        id="nameForm"
        required
      />
    </div>
  );
};
